### ISSUE TITLE
Errors about RTTI settings

### ISSUE THREAD

**Issue by virgil141** [hausfrau87/Boost_PCL_UnrealThirdPartyPlugin#1]
Hi,  Dr. Valentin, I was really excited when i saw your plugin and your methord about how to add these third party library to the project. Your plugin and your article helped me a lot! It solved my problem about loading boost library ,but I found that when I add "bUseRTTI = true;" to my custom cpp class, the compiler will have some warnning and i can't launch my project (A fatal error happens when then engine loaded about 70%). Cause i'm a Chinese student ,my error log in VS2015 is showed in Chinese and maybe hard for you to read ,but i found a really similar Issues here[http://www.smartfoxserver.com/forums/viewtopic.php?f=34&t=19761](url)  
(I'm using Win10 x64, VS2015 and UE4.16 with source)
I've tried adding "UEBuildConfiguration.bForceEnableRTTI = true;" to my project target.cs but seems didn't work. I just don't know what to do.
Waiting for your reply,THX!

**Comment by ValentinKraft** [comment]
Hey Virgil,
ATM I don't know which layout you used for your project, but I'm guessing that you tried to include PCL directly into your project, which won't work, since the "bUseRTTI = true;" will break some Unreal macros (at least I think so). So, you have to create a external module (meaning: a plugin), where you can load the PCL into (you would then write the "bUseRTTI = true;" etc. in the **plugin's** build.cs-file).

Probably it will be the easiest way to just download my github project and use this as a starting point.

**Comment by ValentinKraft** [comment]
actually I just tested again - when you download my github project/plugin, you just have to put "PublicDependencyModuleNames.Add("PCL");"
in your project's build.cs-file and it will work and you'll be able to include the PCL headers/functions in your classes.

When you however want to include PCL/boost as a third-party library yourself, then you have to set the RTTI/Exceptions flags in the module's build.cs-file.

**Comment by virgil141** [comment]
Thanks a lot, Dr. Valentin!
I think i've got what you mean by reading your codes and comments. Just as you say, i tried to include PCL directly into your project and tried to use "pcl::io::loadPCDFile<pcl::PointXYZ>" in my custom Actor Component and now i know that i should make it a module first. 

I think maybe i have to learn more about the unreal module structure before using the library....And sorry for my rudness, may I ask for your social communication program's ID? (Such as QQ and Wechat in China.) I think I have many questions to consult you and it's so inconvenient to ask in git or email. XD
Thanks again!

**Comment by ValentinKraft** [comment]
no problem :D 
you can send me an email to valentin.kraft[at]online.de;)
